name: flutter_flavors
description: "A Flutter project to implement flavors on IOS & Android."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  package_info_plus: ^8.1.1
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
